#!/bin/sh
#copy to /etc/pm/sleep.d
LOGFILE="/var/log/sleep.log"

case "$1" in
        resume|thaw)
                echo "Resumed normal from suspend at `date`" >> "$LOGFILE"
                if [ -f /home/antonio/.btunlock/disable ]; then
                echo "Disabling BT because BTUnlock is disabled"
		su - antonio -c /bin/bash /home/antonio/btunlock/btdisconn.sh 
                fi
		
                ;;
esac
